using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace TMS.Core.Services
{
    public class DispatchContact
    {
        public string Designation { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string TelegramHandle { get; set; } = string.Empty;
    }

    public static class RecordDispatchService
    {
        public static string GetAppDirectory()
        {
            return AppContext.BaseDirectory;
        }

        public static string DispatchesFolder => Path.Combine(GetAppDirectory(), "Dispatches");
        public static string ContactsFilePath => Path.Combine(GetAppDirectory(), "dispatch_contacts.txt");

        static RecordDispatchService()
        {
            try
            {
                if (!Directory.Exists(DispatchesFolder))
                {
                    Directory.CreateDirectory(DispatchesFolder);
                }
            }
            catch { }
        }

        public static List<DispatchContact> LoadContacts()
        {
            var list = new List<DispatchContact>();
            try
            {
                if (File.Exists(ContactsFilePath))
                {
                    string[] lines = File.ReadAllLines(ContactsFilePath);
                    foreach (string line in lines)
                    {
                        if (string.IsNullOrWhiteSpace(line) || line.StartsWith("#")) continue;
                        string[] parts = line.Split('|');
                        if (parts.Length >= 4)
                        {
                            list.Add(new DispatchContact
                            {
                                Designation = parts[0].Trim(),
                                Name = parts[1].Trim(),
                                PhoneNumber = parts[2].Trim(),
                                TelegramHandle = parts[3].Trim()
                            });
                        }
                    }
                }
            }
            catch { }

            if (list.Count == 0)
            {
                list.Add(new DispatchContact { Designation = "Station Master", Name = "Duty SM", PhoneNumber = "+919876543210", TelegramHandle = "@DutySM_Railways" });
                list.Add(new DispatchContact { Designation = "Traffic Controller", Name = "Divisional Controller", PhoneNumber = "+919876543211", TelegramHandle = "@DivControl_SCR" });
                list.Add(new DispatchContact { Designation = "Signal Inspector", Name = "Senior ESM", PhoneNumber = "+919876543212", TelegramHandle = "@SignalDept_HQ" });
            }

            return list;
        }

        public static string FormatDispatchMessage(string regCode, string regTitle, string logId, Dictionary<string, string> fields)
        {
            var sb = new StringBuilder();
            sb.AppendLine("=================================================");
            sb.AppendLine($" INDIAN RAILWAYS - TRAIN MANAGEMENT MEMO");
            sb.AppendLine("=================================================");
            sb.AppendLine($"📋 Log ID: {logId}");
            sb.AppendLine($"🏷️ Register / Authority: {regCode} - {regTitle}");
            sb.AppendLine($"⏰ Timestamp: {DateTime.Now:dd-MM-yyyy HH:mm:ss}");
            sb.AppendLine("-------------------------------------------------");

            foreach (var kvp in fields)
            {
                if (!string.IsNullOrWhiteSpace(kvp.Value))
                {
                    sb.AppendLine($"• {kvp.Key}: {kvp.Value}");
                }
            }

            sb.AppendLine("-------------------------------------------------");
            sb.AppendLine("Official Electronic Memo generated by TMS (Train Management System)");
            sb.AppendLine("=================================================");
            return sb.ToString();
        }

        public static string GenerateWhatsAppUrl(string phoneNumber, string messageText)
        {
            string cleanPhone = phoneNumber.Replace("+", "").Replace(" ", "").Replace("-", "");
            return $"https://wa.me/{cleanPhone}?text={Uri.EscapeDataString(messageText)}";
        }

        public static string GenerateTelegramUrl(string telegramHandle, string messageText)
        {
            string cleanHandle = telegramHandle.TrimStart('@');
            return $"https://t.me/share/url?url=https://t.me/{cleanHandle}&text={Uri.EscapeDataString(messageText)}";
        }
    }
}
